config/routes.rb
Rails.application.routes.draw do
  get 'contact', to: 'contact#index'
  
  get 'blog', to: 'blog#index'

  root 'welcome#index'
  get 'about', to: 'welcome#about'

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/blog_controller.rb
class BlogController < ApplicationController
  def index
  end
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
  def index
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blog_helper.rb
module BlogHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/blog/index.html.erb
<div class="card" >
  
    <div class="card-header">
        <h3>Blog Title</h3>
        <h6 class="card-subtitle mb-2 text-muted">Byline</h6> 
        <h6 class="card-subtitle mb-2 text-muted">Date</h6>        
    </div>
    <div class="card-body">
    <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
    <a href="#" class="card-link">Full Article</a>
    
  </div>
</div>

</br>

<div class="card" >
  
    <div class="card-header">
        <h3>Blog Title</h3>
        <h6 class="card-subtitle mb-2 text-muted">Byline</h6> 
        <h6 class="card-subtitle mb-2 text-muted">Date</h6>        
    </div>
    <div class="card-body">
    <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
    <a href="#" class="card-link">Full Article</a>
    
  </div>
</div>

</br>

<div class="card" >
  
    <div class="card-header">
        <h3>Blog Title</h3>
        <h6 class="card-subtitle mb-2 text-muted">Byline</h6> 
        <h6 class="card-subtitle mb-2 text-muted">Date</h6>        
    </div>
    <div class="card-body">
    <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
    <a href="#" class="card-link">Full Article</a>
    
  </div>
</div>

app/views/contact/index.html.erb
<div class="card text-center"> 
    </br>
    </br>
    <div class="card-body">
        <h1 class="card-title">Contact Us</h1>
        <%# <%= image_tag 'garden3.jpg', :class=>"card-img-top", :alt=>"Rose Campion and Red Hot Poker" %>  
        
        <form>
            <div class="form-group">
            </br>
                <label for="exampleFormControlTextarea1">Please write your message to us below.</label>
                <textarea class="form-control" id="exampleFormControlTextarea1" rows="3">Type your message here...</textarea>
            </div>
            <div class="row">
                <div class="col">
                    <input type="text" class="form-control" placeholder="Name">
                </div>
                <div class="col">
                    <input type="text" class="form-control" placeholder="Email">
                </div>
            </div>
        </form>
        </br>
        <a href="#" class="btn btn-success">Send Message</a>
        </br>
        
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "GardenJournal" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>

    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <h1><%= link_to "Garden Journal ", root_path, class: "navbar-brand" %></h1>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
            <li class="nav-item">
              <%= link_to " Blog ", blog_path, class: "nav-link"  %>
            </li>
            <li class="nav-item">
              <%= link_to " About ", about_path, class: "nav-link"  %>
            </li>
            <li class="nav-item">
              <%= link_to " Sign Up ", new_user_registration_path, class: "nav-link"  %>
            </li>
            <li class="nav-item">
              <%= link_to " Contact ", contact_path, class: "nav-link"  %>
            </li>
          </ul>
        </div>
    </nav>



    <div class="container-fluid">
      <%= yield %>
    </div> <!-- /container -->

    <footer>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <h1 class="navbar-brand">&copy; Garden Journal LLC 2019</h1>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
              <li class="nav-item">
                <%= link_to " Blog ", blog_path, class: "nav-link"  %>
              </li>
              <li class="nav-item">
                <%= link_to " About ", about_path, class: "nav-link"  %>
              </li>
              <li class="nav-item">
                <%= link_to " Sign Up ", new_user_registration_path, class: "nav-link"  %>
              </li>
              <li class="nav-item">
                <%= link_to " Contact ", contact_path, class: "nav-link"  %>
              </li>
            </ul>
          </div>
        </nav>      
    </footer>    

  </body>

</html>

app/views/welcome/about.html.erb
<div class="card text-center">
    <div class="card-body">
        <h1 class="card-title">About Us</h1>
        <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>

        </br>

        <div class="row">
            <div class="card mb-3" style="max-width: 540px;">
                
                    <div class="col-md-8">
                        <%= image_tag '24px.svg', :class=>"card-img-top", :alt=>"Check Mark" %>  
                    </div>
                    <div class="col-md-8">
                        <div class="card-body">
                            <h5 class="card-title">Garden Notes</h5>
                                <p class="card-text">All of your garden reminders and notes in one convenient spot.</p>
                        </div>
                    </div>
                
            </div>

            
            <div class="card mb-3" style="max-width: 540px;">
                
                    <div class="col-md-8">
                        <%= image_tag '24px.svg', :class=>"card-img-top", :alt=>"Check Mark" %>
                    </div>
                    <div class="col-md-8">
                        <div class="card-body">
                            <h5 class="card-title">Plant Inventory</h5>
                                <p class="card-text">Ability to add pictures and notes about specific plants in your collection.</p>
                        </div>
                    </div>
                
            </div>
            <div class="card mb-3" style="max-width: 540px;">
                
                    <div class="col-md-8">
                        <%= image_tag '24px.svg', :class=>"card-img-top", :alt=>"Check Mark" %> 
                    </div>
                    <div class="col-md-8">
                        <div class="card-body">
                            <h5 class="card-title">Reminders</h5>
                                <p class="card-text">Schedule tasks and reminders for tomorrow, next week, or next year.</p>
                        </div>
                    </div>
                
            </div>
        </div>       
    </div>
</div>

app/views/welcome/index.html.erb
<%# <div class="bd-example">
  <div id="carouselExampleCaptions" class="carousel slide" data-ride="carousel">
    <ol class="carousel-indicators">
      <li data-target="#carouselExampleCaptions" data-slide-to="0" class="active"></li>
      <li data-target="#carouselExampleCaptions" data-slide-to="1"></li>
      <li data-target="#carouselExampleCaptions" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner">
      <div class="carousel-item active">
        <%= image_tag 'garden1.jpg', :class=>"d-block w-100", :alt=>"Beds with Porter" %>
<%#        <div class="carousel-caption d-none d-md-block">
          <h5>First slide label</h5>
          <p>Nulla vitae elit libero, a pharetra augue mollis interdum.</p>
        </div>
      </div>
      <div class="carousel-item">
        <%= image_tag 'garden3.jpg', :class=>"d-block w-100", :alt=>"Lilies" %>
<%#        <div class="carousel-caption d-none d-md-block">
          <h5>Second slide label</h5>
          <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</p>
        </div>
      </div>
      <div class="carousel-item">
        <%= image_tag 'garden2.jpg', :class=>"d-block w-100", :alt=>"Rose Campion and Red Hot Poker"%>
<%#        <div class="carousel-caption d-none d-md-block">
          <h5>Third slide label</h5>
          <p>Praesent commodo cursus magna, vel scelerisque nisl consectetur.</p>
        </div>
      </div>
    </div>
    <a class="carousel-control-prev" href="#carouselExampleCaptions" role="button" data-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carouselExampleCaptions" role="button" data-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>
</div> %>

</br>
</br>

<div class="container">
    <div class="row">
        <div class="col-12 md-8">
            <div class="jumbotron jumbotron-fluid">
                <h1 class="display-4"></h1>
                <p class="lead text-center">This will eventualy be a walk through video.</p>
                <hr class="my-4">
                <p class="text-center">Highlighting key features and how to use them.</p>
            </div>
        </div>
    </div>
</div>

</br>

<div class="card text-center">
    <div class="card-body">
        <h1 class="card-title">Main Features</h1>
        <div class="row">
            <div class="card mb-3" style="max-width: 540px;">
                <div class="row no-gutters">
                    <div class="col-md-3">
                        <%= image_tag 'pencil.svg', :class=>"card-img", :alt=>"Check Mark" %>  
                    </div>
                    <div class="col-md-8">
                        <div class="card-body">
                            <h5 class="card-title">Garden Notes</h5>
                                <p class="card-text">All of your garden reminders and notes in one convenient spot.</p>
                        </div>
                    </div>
                </div>
            </div>
            <div class="card mb-3" style="max-width: 540px;">
                <div class="row no-gutters">
                    <div class="col-md-3">
                        <%= image_tag 'flower.svg', :class=>"card-img", :alt=>"Check Mark" %>
                    </div>
                    <div class="col-md-8">
                        <div class="card-body">
                            <h5 class="card-title">Plant Inventory</h5>
                                <p class="card-text">Ability to add pictures and notes about specific plants in your collection.</p>
                        </div>
                    </div>
                </div>
            </div>
            <div class="card mb-3" style="max-width: 540px;">
                <div class="row no-gutters">
                    <div class="col-md-3">
                        <%= image_tag 'calendar.svg', :class=>"card-img", :alt=>"Check Mark" %> 
                    </div>
                    <div class="col-md-8">
                        <div class="card-body">
                            <h5 class="card-title">Reminders</h5>
                                <p class="card-text">Schedule tasks and reminders for tomorrow, next week, or next year.</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>       
    </div>
</div>

<div class="card text-center">    
    <div class="card-body">
        </br>
        <h1 class="card-title">User Image Gallery</h1>
        <p class="card-text">Garden and plant pictures submitted by users.</p>        
    </div>
</div>


<div class="row">
    <div class="col-md-4">
        <div class="card text-center">
        <%= image_tag 'garden4.jpg', :class=>"card-img-top", :alt=>"River Romance Iris" %>        
            <div class="card-body">
                <h5 class="card-title">River Romance Iris</h5>
                <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="card text-center">
        <%= image_tag 'garden3.jpg', :class=>"card-img-top", :alt=>"Rose Campion and Red Hot Poker" %>    
            <div class="card-body">
                <h5 class="card-title">Perennial Bed</h5>
                <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
            </div>
        </div>
    </div>

    <div class="col-md-4">
        <div class="card text-center">
        <%= image_tag 'garden2.jpg', :class=>"card-img-top", :alt=>"Eyeliner Lily" %>    
            <div class="card-body">
                <h5 class="card-title">Eyeliner Lily</h5>
                <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
            </div>
        </div>
    </div>
</div>


<div class="card text-center">    
    <div class="card-body">
        </br>
        </br>
        <h1 class="card-title">Sign Up</h1>
        <p class="card-text">With supporting text below as a natural lead-in to additional content.</p>
        <%= link_to " Sign Up ", new_user_registration_path, class: "btn btn-success"  %>
        </br>
    </div>
</div>

<div class="card text-center"> 
    </br>
    </br>
    <div class="card-body">
        <h1 class="card-title">Contact Us</h1>
        <form>
            <div class="form-group">
                <label for="exampleFormControlTextarea1">Please write your message to us below.</label>
                <textarea class="form-control" id="exampleFormControlTextarea1" rows="3">Type your message here...</textarea>
            </div>
            <div class="row">
                <div class="col">
                    <input type="text" class="form-control" placeholder="Name">
                </div>
                <div class="col">
                    <input type="text" class="form-control" placeholder="Email">
                </div>
            </div>
        </form>
        </br>
        <a href="#" class="btn btn-success">Send Message</a>
    </div>
</div>